---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  type: proxy
  author: Ashwani
spec:
 replicas: 3 
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: nginx-pods
   labels:
    type: proxy
  spec:
   containers:
    - name: mynginx
      image: nginx
      ports: 
       - containerPort: 80
         hostPort: 8080
...           

