--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels: 
    type: mydb
spec:
  replicas: 3
  selector:
    matchLabels:
      type: mydb
  template:
    metadata:
      name: mysql-pod
      labels:
        type: mydb
    spec:  
       containers:
         - name: mydb
           image: mysql
           env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: mysql-secret
                 key: password
...                   
