---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: db-deployment
 labels:
  type: db
  author: Ashwani
spec:
 replicas: 1
 selector:
  matchLabels:
   type: db
 template:
  metadata:
   name: db-pod   
   labels:
    type: db
  spec:
   containers:
    - name: mydb
      image: postgres
      env:
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: pg-secret
             key: password
       - name: POSTGRES_USER
         valueFrom:
           secretKeyRef:
             name: pg-secret
             key: username
       - name: POSTGRES_DB
         valueFrom:
           secretKeyRef:
             name: pg-secret
             key: dbname
...

