---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: mydb
spec:
 containers:
   - name: mydb
     image: postgres
     env:
       - name: POSTGRES_PASSWORD
         value: ash
       - name: POSTGRES_USER
         value: myuser
       - name: POSTGRES_DB
         value: mydb
...          

