---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  containers:
    - name: task-pv-containers
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: task-pv-storage
          mountPath: /usr/share/nginx/html    
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
---




