---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: mydb
    author: Ashwani
spec:
  type: ClusterIP
  selector:
    type: db  
  ports: 
    - targetPort: 5432
      port: 5432 
...    
