---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: Ashwani
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    type: webserver
...


