---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
   name: result-app
spec:
  replicas: 2
  selector:
   matchLabels:
    name: result-app
  template:
   metadata:
    name: result-pod
    labels:
      name: result-app
   spec:
    containers:
     - name: myresult
       image: dockersamples/examplevotingapp_result
...
