---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata: 
     name: worker-pod
     labels:
      name: worker
    spec:
     containers:
      - name: myworker
        image: dockersamples/examplevotingapp_worker 
...          
