---
version: '3'
services:
  voting-app:
    image: docker/example-voting-app-vote
    ports:
      - 5050:80
    deploy:
      replicas: 2
  my-redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    image: docker/example-voting-app-worker
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Ash
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  result-app:
    image: docker/example-voting-app-result
    ports:
      - 6060:80
    deploy:
      replicas: 2
...        
